services:
  db:
    container_name: postgres
    image: postgres:16.2-bookworm
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.5
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13.7-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  django:
    container_name: django
    build: ./todo_list
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - ./todo_list:/app
    depends_on:
      - db
      - rabbitmq

  celery:
    container_name: celery
    build: ./todo_list
    command: celery -A todo_list.celery:app worker -l info
    environment:
      - DEBUG=True
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/postgres
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    volumes:
      - ./todo_list:/app
    depends_on:
      - django
      - rabbitmq

  flower:
    container_name: flower
    build: ./todo_list
    command: celery -A todo_list.celery:app flower -l info
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    ports:
      - "5555:5555"
    depends_on:
      - django
      - rabbitmq
      - celery

volumes:
  db_data: