# Generated by Django 5.0.4 on 2024-06-23 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0003_tasklist_task_todo_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
